### ISSUE TITLE
[BUG] black font color is not correct

### ISSUE THREAD

**Issue by zhaishengfu** [Sudospective/syndibox#10]
I set the font color to black and it does not work
[`0]hello, baby

"[`0]": # Black
			if !escape:
				string.erase(step,4)
				string = string.insert(step,char(8203))
				#if totally black the if judgement will be error
				color = Color("#000000")

I think this is the error of #000000 will be zero or null. I changed this to  Color("#000001") and it worked

**Comment by Sudospective** [comment]
What version of Godot are you using? I haven't tested with 3.2 but 3.1 works just fine.

**Comment by zhaishengfu** [comment]
tested with 3.2

**Comment by Sudospective** [comment]
I've confirmed that 3.2 has a little bit of different logic when dealing with color #000000. This was changed in a recent merge, and I'm planning to set a 1.5.2 release soon.
