### ISSUE TITLE
[BUG] manual advance causes text effect triggers to not work

### ISSUE THREAD

**Issue by thegrumpybuffalo** [Sudospective/syndibox#11]
**Describe the bug**

**To Reproduce**
1. create a sandbox object with auto advance disabled
2. attempt to play dialog in a scene and manual advance with ui_accept (default: enter key)
3. see that any in text tags get read in plain text

**Expected behavior**
any tags used should work in both auto and manual advance modes

**Platform**
 - OS: Mac OSX
 - Godot 3.2

**Comment by Sudospective** [comment]
Thanks for the bug report, I'll look into it in the future. Right now my living situation is very up in the air and I'm trying to get stable, but as soon as I have the chance, I'll start working on fixing all the bugs reported.

**Comment by Sudospective** [comment]
Fixed in 1.5.3, probably even sooner, can't recall, been a long while
