### ISSUE TITLE
[BUG] Profile image out of position

### ISSUE THREAD

**Issue by ron0studios** [Sudospective/syndibox#13]
**Describe the bug**
icons have strange offsets

**To Reproduce**
1. add profile image
2. the image is placed miles away from the actual textbox

**Expected behavior**
The icon should be under the label and on the left of the text

Im going to make a pull request soon on fixing this because i think i can see whats happening!

**Comment by Sudospective** [comment]
I think it's because I rushed that addition and hardcoded it at the time. I need to change the code for the profiles when I get the chance, almost finished moving in to my apartment.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
So i been playing around with this addon and i think the problem had something to do with the anchor as in the default position it a far away but if you adjust the anchor to be closer to the box it is much closer to how it should be.

i am going to see if i can try to fix that
