### ISSUE TITLE
[BUG] Occasionally, text effects do not register

### ISSUE THREAD

**Issue by ron0studios** [Sudospective/syndibox#20]
**Describe the bug**
sometimes, when Im using autoadvance, the text effects don't register (e.g shake effect doesn't cause the text to shake but it's not written out as plain text, unlike other bugs)

**To Reproduce**
1. make a syndibox instance, on autoadvance, set some text.
2. add shake [^v]
3. occasional error, 1 in 5

**Expected behavior**
It should always shake

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version Godot 3.2

**Additional context**
What is the escape variable. It says that it is depreceted, you could remove it?
im working on a full time project with this please could you find a solution?

**Comment by Sudospective** [comment]
This was a problem with the random math involved, fixed it to be constant rather than variable
