### ISSUE TITLE
[BUG] Invalid get index '0' (on base: 'Nil').

### ISSUE THREAD

**Issue by hero-clashes** [Sudospective/syndibox#21]
**Describe the bug**
Invalid get index '0' (on base: 'Nil'). at line 696 and 195

**To Reproduce**
i just try to make the same test you did
**Expected behavior**
crash
**Screenshots**
If applicable, add screenshots [to ](url
![بدون عنوان](https://user-images.githubusercontent.com/20283475/86302146-2da88300-bc08-11ea-9565-a748794e6dcb.png)
).

**Desktop (please complete the following information):**
 - OS: windous 8
 - Version 3.2.2

**Comment by Sudospective** [comment]
It seems it's trying to find the first character of a null string, which of course would be null. How do you have your dialog set up? Are you using the property for it on the side or do you have it pulling the string in another way?

**Comment by hero-clashes** [comment]
yes i am using the property on the side with random text

**Comment by hero-clashes** [comment]
and no i am not trying to pull it in another way

**Comment by hero-clashes** [comment]
![1](https://user-images.githubusercontent.com/20283475/86360877-469a4e00-bc73-11ea-900e-cd7dee311d8d.png)
![2](https://user-images.githubusercontent.com/20283475/86360895-4c902f00-bc73-11ea-82dd-04ed2a854270.png)

**Comment by hero-clashes** [comment]
thats all what i did

**Comment by Sudospective** [comment]
Are you able to send an isolated example of this bug from your project? That would very much help me with understanding what's going on here. I can't recreate this bug on my own.

**Comment by hero-clashes** [comment]
i am sorry that i took so long time but it will be helpful if you could fix it
and thank you for taking time and effort you are a great human
 here my project (just started :) )
[test.zip](https://github.com/Sudospective/syndibox/files/4899277/test.zip)

**Comment by Sudospective** [comment]
Thanks! I'll try it out once I get time at my laptop. I'm very patient, and want to make sure everything works as it should. Once I figure out this issue, I'll fix another issue I've been working at and I'll push the changes to a new release for 1.6.0.

**Comment by hero-clashes** [comment]
> Thanks! I'll try it out once I get time at my laptop. I'm very patient, and want to make sure everything works as it should. Once I figure out this issue, I'll fix another issue I've been working at and I'll push the changes to a new release for 1.6.0.

what a fast replay i am looking forward to it 
and thanks once more

**Comment by hero-clashes** [comment]
just tried opening SyndiBox.tscn and it gave this error
![3](https://user-images.githubusercontent.com/20283475/87088138-8ee9db00-c234-11ea-972f-e0801e632c2f.png)

**Comment by Darenn** [comment]
Hi, same problem than @hero2002 here.

**Comment by Sudospective** [comment]
I'm pending a release that fixes this issue. Not sure why it was reading the DIALOG exported var as null, but it's fixed now. Watch for the next update on the Releases tab and the Godot Asset Lib coming over the next few days.

**Comment by hero-clashes** [comment]
Thanks
