### ISSUE TITLE
Is this support Godot's BBCode?

### ISSUE THREAD

**Issue by Jeremi360** [Sudospective/syndibox#22]
Is this support Godot's BBCode like Godot's RichText Control ?
I ask because I think about adapting this project for [Rakugo](https://github.com/rakugoteam/Rakugo) 
and Rakugo make heavy use of this feature.

**Comment by Sudospective** [comment]
BBCode isn't currently supported by SyndiBox. However, if I recall correctly, there is someone who has set up a fork for a Rakugo adaptation. You might have better luck checking where they're at with this fork.

As for now, I don't necessarily plan to support BBCode. However, if I find something that BBCode can help me do better than what I'm currently doing on the project, specifically positional effects, I would definitely consider adding it.
