### ISSUE TITLE
[BUG] Divide by 0

### ISSUE THREAD

**Issue by zaknafean** [Sudospective/syndibox#28]
**Describe the bug**
Syndibox crashes with divide by 0 error if top left margin = 0. This is easily worked around by changing the value, but was also the very first thing to happen to me when I used the plugin.

**To Reproduce**
1. Add  Syndibox Node to scene
2. Start Scene
3. Crash

**Expected behavior**
No crashes and for it to behave as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/7741797/96453127-093cda80-11e8-11eb-8c3e-bea5bde045d1.png)

**Version**
- Godot Version 3.2.3

**Additional context**
Technically the node is about 4 deep from scene root, and is a child of a non-control node. This may be part of the cause.

**Comment by Sudospective** [comment]
oh thats bad

I'll get to fixing that, thank you for sharing this

**Comment by zaknafean** [comment]
Playing around with this more, it also happens when its a child of control nodes too. So its really just the 0 itself thats the problem.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
It probably because of my profile picture bug fix

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
I think i just found a fix, i am adding it to my pull request right now
