### ISSUE TITLE
[BUG] Icon is missing on the asset library

### ISSUE THREAD

**Issue by Calinou** [Sudospective/syndibox#3]
**Describe the bug**

The icon is missing on the [add-on's asset library page](https://godotengine.org/asset-library/asset/415). I suggest uploading a 64×64 icon to GitHub, then link to the "raw" URL directly in the icon URL field. (This icon can also be 128×128 to support hiDPI displays.)

The raw URL is the one of the form `https://raw.githubusercontent.com/Sudospective/syndibox/master/path/to/file.ext`.

**Screenshots**

![image](https://user-images.githubusercontent.com/180032/66503365-62e3d280-eac7-11e9-8b9f-93cb4c0077cb.png)

**Comment by Sudospective** [comment]
Website was temporarily down. Switched to a GitHub raw, should be fixed.

**Comment by Calinou** [comment]
Thanks! It's working now :slightly_smiling_face:
