### ISSUE TITLE
[BUG] "res://Objects/HUD/TextPanel.tscn" dependency in main SyndiBox.tscn file

### ISSUE THREAD

**Issue by zaknafean** [Sudospective/syndibox#39]
**Describe the bug**
Attempting to open the SyndiBox.tscn results in a failed load due to missing dependency. I assume this is part of some previous version or project. Obviously the SyndiBox functions without this dependency, but it is certainly weird to have.

**To Reproduce**
1. Properly install the SyndiBox addon
2. Try to open the SyndiBox.tscn
3. See screenshot

**Expected behavior**
Being able to open the scene and take a look around would be the expected result. Even the Open Anyway function fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/7741797/97193054-f5145280-177e-11eb-959c-2b8daf092e85.png)

**Device Info (please complete the following information):**
 - OS: Windows 10
 - Godot version: 3.23.
 - SyndiBox version: 1.7.1

**Additional context**
I was actually just curious about the character protrait and other stuff hinted at in the Custom.gd so its the first time I've ever tried to open the actual scene directly.

**Comment by Sudospective** [comment]
Huh, that's really weird, that should have definitely been included...I'll fix that soon.

**Comment by Sudospective** [comment]
i dont remember if i did this did i do this

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
Not yet

**Comment by Sudospective** [comment]
Fixed, will be pushing soon
