### ISSUE TITLE
[BUG] Position effects don't trigger in current godot

### ISSUE THREAD

**Issue by CJCarns** [Sudospective/syndibox#4]
**Describe the bug**
`if tween_start && tween_end:`
The line of code above does not trigger for the [^t] tag, possibly other tags. The reason is that Godot treats Vector2(0, 0) to be false. This is the value set to the tween_start for that tag, and so the condition is not met. When using a value other than the zero vector it works. Take this into account and rework the position trigger perhaps.

**To Reproduce**
1. Create some text with [^t] tag

**Expected behavior**
Text should bounce.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Godot: 3.1.2.stable

**Comment by CJCarns** [comment]
If you would like me to make changes for this I could. I also modified the code to support exported alternative fonts and a font tag for just fonts. I could also do the same for custom colors that aren't hard coded. I love your plugin, thank you.

**Comment by Sudospective** [comment]
If you make a pull request, I'll review it and add those changes. I'm very glad someone else wants to help with this thing, I've been swamped with work and other projects. I'm happy you like it thank you I worked hard on it ;w;
