### ISSUE TITLE
Rakugo support

### ISSUE THREAD

**Issue by Jeremi360** [Sudospective/syndibox#7]
Hi, I'm creating [Rakugo Framework](https://github.com/rakugoteam/Rakugo) for Godot.
It is a equvialent of Ren'Py for Godot.
After I finish work on current 2.1.00 I want to change Rakugo gui to use your syndibox instead of RichTextLabel in next relase.
Will you help me?

**Comment by Sudospective** [comment]
I suppose I can start a branch, but I've been swamped with other dev work since the end of last year. I'll see what I can do, though.

EDIT: Feel free to DM me on Discord (Sudospective#3479) and I'll try to help with whatever you need.

**Comment by Jeremi360** [comment]
Thanks, @Sudospective for fast anwser.
No problem, work is work.
I will probably fork this and include this for into Rakugo.
I will DM you on Discord if I will need any help.
