### ISSUE TITLE
Maybe Add Signals? [Text_finished] [text_is_paused]

### ISSUE THREAD

**Issue by moizez102** [Sudospective/syndibox#8]
Good morning, I have been testing your plugin and the truth is that it is fantastic, however I feel that it is missing that in some part of the text you can call a signal, something like “text_is_paused” or "text_finished" in order  to take action once the text has finished or use the text during a scene that has animations in between

I tried to do it myself but, as you put in the code, it's a huge headache, and I really don't understand 99% of it xD

so I thought it would be better to give you the idea and when you have some time, maybe you can implement it.....or not

by the way, excuse my bad English, I hope you can understand the idea and have a beautifull day <3

**Comment by Sudospective** [comment]
I have to admit, some of this code was made before I was really comfortable with using signals, but I'll give it a shot to maybe rewrite some of it for that. But so far, I haven't had much of a need for it. I will admit, a signal would definitely be cleaner, so I am considering this. Thanks for the suggestion!

**Comment by Sudospective** [comment]
Just letting you know that these were added in pull request #15 \o/
